### ISSUE TITLE
升级到go1.9后有BUG

### ISSUE THREAD

**Issue by mackyzhan** [ccsexyz/shadowsocks-go#1]
本机win10_ADM64
"obfs":false,
"obfsalive":true,
"mux":true,
"partenchttps":false

1.8编译的时候提示sync.Map未定义，查了一下需要升级到go1.9。
升级后顺利编译运行客户端，发现shadowsocks.DialSSWithRawHeader触发panic:slice bounds out of range,
查了一下源码，估计是这一行port := binary.BigEndian.Uint16(header[len(header)-2:])中header数组的长度小于2了

**Comment by ccsexyz** [comment]
已修复，不过现在不建议使用mux，因为这个被我瞎改改出bug了好像。

**Comment by mackyzhan** [comment]
我看你提交的代码只是不让报错，没根本解决，不过你自己用的，单子关了

**Comment by ccsexyz** [comment]
你说的根本解决是什么意思

**Comment by mackyzhan** [comment]
只是不报错了，但mux开启和关闭都无法连接服务器。
我试了下Pre-release v20170903这个版本能正常使用

**Comment by ccsexyz** [comment]
报错的原因是slice溢出后程序崩溃，提交的代码的目的就是避免溢出。而mux的bug那是另外一个bug，这是两码事。
